name = "lapce-perl"
version = "0.1.0"
author = "jan"
display-name = "Perl"
description = "Perl for Lapce"
wasm = "lapce-perl.wasm"
icon = "perl-logo.png"
repository = "https://github.com/janlimpens/lapce-perl"

[activation]
language = ["perl"]
workspace-contains = []

[config."lsp.perl_languageserver.serverPath"]
default = "~/perl5/bin/pls"
description = "Path to Perl::LanguageServer executable"

